title: Baitboat Technology Wiki
description: The wiki for BBT hardware and the Baitboat Autopilot app

remote_theme: just-the-docs/just-the-docs

# Custom domain
url: "https://wiki.baitboat.tech"
baseurl: ""

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag

just_the_docs:
  logo: "/assets/logo.png"   # remove if you don't have it yet
  search_enabled: true
  heading_anchors: true
  nav_sort: case_insensitive
  aux_links:
    "GitHub Repo": "https://github.com/OwenRay/bbt-wiki"
